### ISSUE TITLE
Updating the same element with same value in loop

### ISSUE THREAD

**Issue by eidosam** [gisaac85/hyf-Javascript2#1]
This line can be outside the loop https://github.com/gisaac85/hyf-Javascript2/blob/3aa7813a46808864a6af110d535319de4b5f2fef/week1/test.js#L136

It is applied on one element doesn't change and given the same value, maybe you can move it to line 119?

**Comment by gisaac85** [comment]
Yes I must put it out loop

**Comment by eidosam** [comment]
Solved in 5dd8e7cd1241e223647625fdbd85fc217999a2b2
