### ISSUE TITLE
Redundant block of code

### ISSUE THREAD

**Issue by eidosam** [gisaac85/hyf-Javascript2#2]
What is the purpose of these lines? https://github.com/gisaac85/hyf-Javascript2/blob/3aa7813a46808864a6af110d535319de4b5f2fef/week1/test.js#L196-L212

I see comment `//for loop to add books' covers`, but they are already added in the previous block.
And the elements created not added to the document

**Comment by gisaac85** [comment]
As I understood I made loop to add covers image and loop to add links of covers image !

**Comment by gisaac85** [comment]
This loop here is to add src attribute to img!!

**Comment by eidosam** [comment]
Solved in b2cedef443ca186c84044ee47e27a741aed48584
